spring.application.name: modulith
spring.profiles.active: local

server:
  port: 8090

spring:
  docker:
    compose:
      lifecycle-management: start_only
  sql:
    init:
      mode: always

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: prod

---
spring.config.activate.on-profile: test
